unpackaged/main/default/objects/CM_Location__c/CM_Location__c.object-meta.xml
<CustomObject>
    <description>Case Related Locations are used to hold location information related to cases, such as the address of doctors and what type of medical assistance provided there.</description>
    <label>CM Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CM_Location__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <description>Intake this location is attached to.</description>
    <inlineHelpText>Intake this location is attached to.</inlineHelpText>
    <label>Intake</label>
    <referenceTo>litify_pm__Intake__c</referenceTo>
    <relationshipName>Case_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/CM_Location__c/fields/Medical_Type__c.field-meta.xml
<CustomField>
    <fullName>Medical_Type__c</fullName>
    <description>Used by D&amp;C to determine the type of medical information used, whether it is a facility or an individual provider.(I think)</description>
    <label>Medical Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Medical_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Medical_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Facility</fullName>
    </customValue>
    <customValue>
        <fullName>Provider</fullName>
    </customValue>
    <description>Used by D&amp;C to outline the medical info about a location visited.</description>
    <masterLabel>Medical Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CMLocationTriggerHandler.cls
//Created 03/05/25 by Scott Purcell
public class CMLocationTriggerHandler {
    public static boolean ranOnce = false;
    public static void isAfterInsert(List<CM_Location__c> locations){
        List<String>firstNames = new List<String>();
        List<String>lastNames = new List<String>();
        List<String>cities = new List<String>();
        List<String>addresses = new List<String>();
        List<String>zips = new List<String>();
        List<Id>intakeIds = new List<Id>();
        List<Id>dupes = new List<Id>();
        ranOnce = true;
        for(CM_Location__c loc:locations){
            cities.add(loc.Business_CompoundAddress__City__s);
            addresses.add(loc.Business_CompoundAddress__Street__s);
            zips.add(loc.Business_CompoundAddress__PostalCode__s);
            intakeIds.add(loc.Intake__c);
        }
        List<CM_Location__c>existingLocations = [Select Id,Medical_Type__c,Intake__c,Business_CompoundAddress__City__s,
                                                Business_CompoundAddress__Street__s,Business_CompoundAddress__PostalCode__s 
                                                From CM_Location__c 
                                                Where Business_CompoundAddress__City__s IN: cities
                                                AND Business_CompoundAddress__Street__s IN: addresses
                                                AND Business_CompoundAddress__PostalCode__s IN: zips
                                                AND Intake__c IN: intakeIds
                                                AND Id NOT IN:locations
                                               ];
        system.debug('ExistingLocations: '+existingLocations);
        if(existingLocations.size()>0){
            for(CM_Location__c loc:locations){
                for(CM_Location__c eloc:existingLocations){
                    if( loc.Medical_Type__c == eloc.Medical_Type__c
                       && loc.Business_CompoundAddress__City__s == eloc.Business_CompoundAddress__City__s 
                       && loc.Business_CompoundAddress__Street__s == eloc.Business_CompoundAddress__Street__s 
                       && loc.Business_CompoundAddress__PostalCode__s == eloc.Business_CompoundAddress__PostalCode__s
                       && loc.Intake__c == eloc.Intake__c){
                          system.debug('dupe added: '+loc);
                           dupes.add(loc.Id);
                       }
                }
            }
        }
        removeDuplicateLocation(dupes);
    }
    
    @future
    public static void removeDuplicateLocation(List<Id>dupes){
        try{
            system.debug('dupes: '+dupes);
            Database.delete(dupes);
        }catch(Exception e){
            system.debug('Exception: '+ e);
        }
    }
}