unpackaged/main/default/objects/CM_Location__c/CM_Location__c.object-meta.xml
<CustomObject>
    <description>Case Related Locations are used to hold location information related to cases, such as the address of doctors and what type of medical assistance provided there.</description>
    <label>CM Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CM_Location__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <description>Intake this location is attached to.</description>
    <inlineHelpText>Intake this location is attached to.</inlineHelpText>
    <label>Intake</label>
    <referenceTo>litify_pm__Intake__c</referenceTo>
    <relationshipName>Case_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/CM_Location__c/fields/Medical_Type__c.field-meta.xml
<CustomField>
    <fullName>Medical_Type__c</fullName>
    <description>Used by D&amp;C to determine the type of medical information used, whether it is a facility or an individual provider.(I think)</description>
    <label>Medical Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Medical_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CM_Location__c/fields/Provider_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_First_Name__c</fullName>
    <description>First name of the provider seen at that location, whether it is a doctor, pharmacist, staff, etc.</description>
    <inlineHelpText>First name of the primary provider at the location</inlineHelpText>
    <label>Provider First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CM_Location__c/fields/Provider_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Last_Name__c</fullName>
    <description>Last name of the provider seen at that location, whether it is a doctor, pharmacist, staff, etc.</description>
    <inlineHelpText>Last name of the primary provider at location</inlineHelpText>
    <label>Provider Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Medical_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Facility</fullName>
    </customValue>
    <customValue>
        <fullName>Provider</fullName>
    </customValue>
    <description>Used by D&amp;C to outline the medical info about a location visited.</description>
    <masterLabel>Medical Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CMLocationTriggerHandler_Test.cls
@isTest
public class CMLocationTriggerHandler_Test {
	@isTest
    public static void testDeletionOfFirstLocation(){
        String ani='1112225555';
        IntakeTriggerHandler.ani = ani;
		litify_pm__Intake__c inta = new litify_pm__Intake__c(litify_pm__Phone__c=ani);
        insert inta;
        
        CM_Location__c location = new CM_Location__c();
        location.Provider_First_Name__c = 'Test';
        location.Provider_Last_Name__c = 'Lasty';
        location.Business_CompoundAddress__City__s = 'Provo';
        location.Business_CompoundAddress__Street__s = '1234 north 1400 west';
        location.Business_CompoundAddress__PostalCode__s = '84058';
        location.Medical_Type__c = 'Provider';
        location.Intake__c = inta.Id;
        
        test.startTest();
        CMLocationTriggerHandler.ranOnce = false;
        insert location;
        List<CM_Location__c>existingLocations = [Select Id,Business_CompoundAddress__City__s,Business_CompoundAddress__Street__s,Business_CompoundAddress__PostalCode__s 
                                                From CM_Location__c];
        system.assert(existingLocations.size()==1,'There should be 1 location');
        Test.stopTest();
                                               
    }
    
    @isTest
    public static void testDuplicateLocations(){
        String ani='1112225555';
        IntakeTriggerHandler.ani = ani;
		litify_pm__Intake__c inta = new litify_pm__Intake__c(litify_pm__Phone__c=ani);
        insert inta;
        
        CM_Location__c location = new CM_Location__c();
        location.Business_CompoundAddress__City__s = 'Provo';
        location.Business_CompoundAddress__Street__s = '1234 north 1400 west';
        location.Business_CompoundAddress__PostalCode__s = '84058';
        location.Medical_Type__c = 'Provider';
        location.Intake__c = inta.Id;
        location.Provider_First_Name__c = 'Test';
        location.Provider_Last_Name__c = 'Lasty';
        CMLocationTriggerHandler.ranOnce = true;
        insert location;
        
        CM_Location__c location2 = new CM_Location__c();
        location2.Business_CompoundAddress__City__s = 'Provo';
        location2.Business_CompoundAddress__Street__s = '1234 north 1400 west';
        location2.Business_CompoundAddress__PostalCode__s = '84058';
        location2.Medical_Type__c = 'Provider';
        location2.Provider_First_Name__c = 'Test2';
        location2.Provider_Last_Name__c = 'Lasty2';
        location2.Intake__c = inta.Id;
        
        test.startTest();
        CMLocationTriggerHandler.ranOnce = false;
        insert location2;
        
        Test.stopTest();
        List<CM_Location__c>existingLocations = [Select Id,Business_CompoundAddress__City__s,Business_CompoundAddress__Street__s,Business_CompoundAddress__PostalCode__s 
                                                From CM_Location__c];
        system.assert(existingLocations.size()==1,'There should be 1 location');
                                               
    }
}