unpackaged/main/default/objects/Dropbox_Sign_API_Settings__c/Dropbox_Sign_API_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Dropbox Sign API Settings</label>
</CustomObject>

unpackaged/main/default/objects/Dropbox_Sign_API_Settings__c/fields/Base_URL__c.field-meta.xml
<CustomField>
    <fullName>Base_URL__c</fullName>
    <label>Base URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Dropbox_Sign_API_Settings__c/fields/Log_Days_to_Keep__c.field-meta.xml
<CustomField>
    <fullName>Log_Days_to_Keep__c</fullName>
    <label>Log Days to Keep</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log (Outgoing)</label>
    <nameField>
        <label>Integration Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Logs (Outgoing)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Integration_Log__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>Stop__c -  Start__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <label>Stop</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/DropboxSignAPILoggerTest.cls
@isTest
public with sharing class DropboxSignAPILoggerTest {
    private static Dropbox_Sign_API_Settings__c createTestDropboxSignAPISettings(){
        Dropbox_Sign_API_Settings__c setting = new Dropbox_Sign_API_Settings__c();
        setting.Debugging__c = true;
        setting.Log_Days_to_Keep__c = 90;
        setting.Log_Levels__c = 'ERROR, INFO, DEBUG';
        setting.Base_URL__c = 'https://api.hellosign.com/v3';
        setting.API_Key__c = '123';
        insert setting;
        return setting;
    }
    @IsTest static void testLog() {
        createTestDropboxSignAPISettings();
        Test.startTest();
            // default settings
            System.assertEquals(0, [SELECT Count() FROM Integration_Log__c]);

            // nothing to write
            DropboxSignAPILogger.writeLogs();
            System.assertEquals(0, [SELECT Count() FROM Integration_Log__c]);

            new DropboxSignAPILogger.Log(null, 'none1');
            DropboxSignAPILogger.writeLogs();
            System.assertEquals(0, [SELECT Count() FROM Integration_Log__c]);

            new DropboxSignAPILogger.Log(LoggingLevel.FINE, 'fine1');
            DropboxSignAPILogger.writeLogs();
            System.assertEquals(0, [SELECT Count() FROM Integration_Log__c]);

            // REST log
            new DropboxSignAPILogger.Log(LoggingLevel.DEBUG, 'debug1');
            DropboxSignAPILogger.Log l = new DropboxSignAPILogger.Log(LoggingLevel.ERROR, 'error1', 'sum1');
            l.setRequest(null);
            l.setResponse(null);
            l.start();
            l.stop();
            DropboxSignAPILogger.writeLogs();
            System.assertEquals(2, [SELECT Count() FROM Integration_Log__c]);
            System.assertEquals(1, [SELECT Count() FROM Integration_Log__c WHERE Name = 'error1'
                AND Level__c = 'ERROR' AND Start__c != null AND Stop__c != null AND Duration__c != null]);

            new DropboxSignAPILogger.Log(LoggingLevel.DEBUG, null).toString();
            new DropboxSignAPILogger.Log(LoggingLevel.DEBUG, null).getElapsed();
        Test.stopTest();
    }
}