unpackaged/main/default/objects/Account/fields/Date_of_Death__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Death__c</fullName>
    <label>Date of Death</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Intake_Client_Count__c.field-meta.xml
<CustomField>
    <fullName>Intake_Client_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>DLRS Rollup - count of intakes where this party is Client</description>
    <inlineHelpText>DLRS Rollup - count of intakes where this party is Client</inlineHelpText>
    <label>Intake Client Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Answer__c/fields/Criteria_Met__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Met__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Criteria Met</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Answer__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <label>Intake</label>
    <referenceTo>litify_pm__Intake__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Answer__c/fields/Questionnaire_Question__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire_Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question</label>
    <referenceTo>Questionnaire_Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Questionnaire__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>litify_pm__Case_Type__c.litify_pm__Is_Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>litify_pm__Case_Type__c</referenceTo>
    <relationshipLabel>Questionnaires</relationshipLabel>
    <relationshipName>Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire__c/fields/isAvailable__c.field-meta.xml
<CustomField>
    <fullName>isAvailable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Question__c/Questionnaire_Question__c.object-meta.xml
<CustomObject>
    <label>Questionnaire Question</label>
    <nameField>
        <label>Questionnaire Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaire Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Questionnaire_Question__c/fields/Conditional_Field__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Field__c</fullName>
    <label>Conditional Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Question__c/fields/Conditional_Object__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Object__c</fullName>
    <label>Conditional Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake__c</fullName>
                <label>Intake</label>
            </value>
            <value>
                <fullName>Intake__r.Campaign_Case__c</fullName>
                <label>Campaign Case</label>
            </value>
            <value>
                <fullName>Questionnaire_Question__c</fullName>
                <label>Questionnaire Question</label>
            </value>
            <value>
                <fullName>Questionnaire_Question__r.Questionnaire_Section__c</fullName>
                <label>Questionnaire Section</label>
            </value>
            <value>
                <fullName>Intake__r.litify_pm__Client__c</fullName>
                <label>Account</label>
            </value>
            <value>
                <fullName>Intake__r.srlg_Injured_Party__c</fullName>
                <label>Injured Party</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Question__c/fields/Conditional_Value__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Value__c</fullName>
    <inlineHelpText>Criteria that must be met to show the question. If left blank then it will always show.</inlineHelpText>
    <label>Conditional Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Question__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Questionnaire Questions</relationshipLabel>
    <relationshipName>QuestionnaireQuestion</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Question__c/fields/Questionnaire_Section__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire_Section__c</fullName>
    <label>Questionnaire Section</label>
    <referenceTo>Questionnaire_Section__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>QuestionSection</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Section__c/Questionnaire_Section__c.object-meta.xml
<CustomObject>
    <label>Questionnaire Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaire Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Questionnaire_Section__c/fields/Conditional_Object__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Object__c</fullName>
    <label>Conditional Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake__c</fullName>
                <label>Intake</label>
            </value>
            <value>
                <fullName>Intake__r.Campaign_Case__c</fullName>
                <label>Campaign Case</label>
            </value>
            <value>
                <fullName>Intake__r.litify_pm__Client__c</fullName>
                <label>Account</label>
            </value>
            <value>
                <fullName>Intake__r.srlg_Injured_Party__c</fullName>
                <label>Injured Party</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Section__c/fields/Conditional_Operator__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Operator__c</fullName>
    <label>Conditional Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Operators</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Section__c/fields/Conditional_Value__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Value__c</fullName>
    <inlineHelpText>Criteria that would need to be met to be visible. If blank then always visible.</inlineHelpText>
    <label>Conditional Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Section__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Questionnaire</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Section__c/fields/Section_Category__c.field-meta.xml
<CustomField>
    <fullName>Section_Category__c</fullName>
    <label>Section Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Short Form</fullName>
            </value>
            <value>
                <fullName>Long Form</fullName>
            </value>
            <value>
                <fullName>Qualifying</fullName>
                <isActive>false</isActive>
                <label>Qualifying</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/srlg_Injured_Party__c/srlg_Injured_Party__c.object-meta.xml
<CustomObject>
    <label>Injured Party</label>
    <nameField>
        <label>Injured Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Injured Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/srlg_Injured_Party__c/fields/Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Birth__c</fullName>
    <label>Date Of Birth</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/srlg_Injured_Party__c/fields/Date_Of_Death__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Death__c</fullName>
    <label>Date Of Death</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/srlg_Injured_Party__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>litify_pm__Intake__c</referenceTo>
    <relationshipLabel>Injured Parties</relationshipLabel>
    <relationshipName>Injured_Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Operators.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>equals</fullName>
    </customValue>
    <customValue>
        <fullName>not equals</fullName>
    </customValue>
    <customValue>
        <fullName>less than</fullName>
    </customValue>
    <customValue>
        <fullName>less or equals</fullName>
    </customValue>
    <customValue>
        <fullName>greater than</fullName>
    </customValue>
    <customValue>
        <fullName>greater or equals</fullName>
    </customValue>
    <customValue>
        <fullName>starts with</fullName>
    </customValue>
    <customValue>
        <fullName>ends with</fullName>
    </customValue>
    <customValue>
        <fullName>contains</fullName>
    </customValue>
    <description>Valid Operators for dynamic criteria calculations</description>
    <masterLabel>Operators</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/DynamicAnswerCriteriaEvaluatorTest.cls
/**
 * @description       : Unit tests for DynamicAnswerCriteriaEvaluator
 * @group             : Questionnaire
 * @last modified on  : 2025-05-12
 * @last modified by  : Jacob Barnett - SaltClick
**/
@IsTest
public class DynamicAnswerCriteriaEvaluatorTest {

    private static Account createTestAccount() {
        Account acct = new Account(
            Name = 'Test Account',
            litify_pm__Last_Name__c = 'Test Last',
            litify_pm__Phone_Home__c = '555-123-4567',
            NumberOfEmployees = 10,
            Intake_Client_Count__c = 1
        );
        insert acct;
        return acct;
    }

    private static litify_pm__Case_Type__c createTestCaseType() {
        litify_pm__Case_Type__c ct = new litify_pm__Case_Type__c(
            Name = 'Test Case Type',
            litify_pm__Is_Available__c = true
        );
        insert ct;
        return ct;
    }

    private static litify_pm__Intake__c createTestIntake(Id acctId, Id caseTypeId) {
        litify_pm__Intake__c intake = new litify_pm__Intake__c(
            litify_pm__Client__c = acctId,
            litify_pm__Case_Type__c = caseTypeId,
            Test_Intake__c = true,
            Count_of_E_Sig_Documents__c = 10,
            Injured_Party_Birthdate__c = Date.today().addYears(-30),
            Date_Last_Modified_by_API__c = Datetime.now().addHours(-24)
        );
        insert intake;
        return intake;
    }

    private static Map<String, Id> createQuestionnaireWithSection(Id caseTypeId) {
        Questionnaire__c q = new Questionnaire__c(
            isActive__c = true,
            isAvailable__c = true,
            Case_Type__c = caseTypeId
        );
        insert q;

        Questionnaire_Section__c section = new Questionnaire_Section__c(
            Questionnaire__c = q.Id,
            Section_Category__c = 'Short Form'
        );
        insert section;

        return new Map<String, Id>{
            'questionnaireId' => q.Id,
            'sectionId' => section.Id
        };
    }

    @IsTest static void verifyFullEvaluationAgainstChildObject() {
        Account acct = createTestAccount();
        litify_pm__Case_Type__c caseType = createTestCaseType();
        litify_pm__Intake__c intake = createTestIntake(acct.Id, caseType.Id);
        Map<String, Id> ids = createQuestionnaireWithSection(caseType.Id);
        Id sectionId = ids.get('sectionId');
        Id questionnaireId = ids.get('questionnaireId');

        srlg_Injured_Party__c injuredParty = new srlg_Injured_Party__c(
            Intake__c = intake.Id,
            Date_Of_Birth__c = Date.today().addYears(-15),
            Date_Of_Death__c = Date.today().addYears(-1),
            First_Name__c = 'test first',
            Last_Name__c = 'test last'
        );
        insert injuredParty;

        List<Questionnaire_Question__c> questions = new List<Questionnaire_Question__c>{
            new Questionnaire_Question__c(
                Questionnaire_Section__c = sectionId,
                Questionnaire__c = questionnaireId,
                Conditional_Object__c = 'Intake__r.srlg_Injured_Party__c',
                Conditional_Field__c = 'Date_Of_Death__c',
                Conditional_Operator__c = 'less or equals',
                Conditional_Value__c = String.valueOf(Date.today())
            ),
            new Questionnaire_Question__c(
                Questionnaire_Section__c = sectionId,
                Questionnaire__c = questionnaireId,
                Conditional_Object__c = 'Intake__r.srlg_Injured_Party__c',
                Conditional_Field__c = 'Date_Of_Birth__c',
                Conditional_Operator__c = 'greater than',
                Conditional_Value__c = String.valueOf(Date.today().addYears(-20))
            ),
            new Questionnaire_Question__c(
                Questionnaire_Section__c = sectionId,
                Questionnaire__c = questionnaireId,
                Conditional_Object__c = 'Intake__r.srlg_Injured_Party__c',
                Conditional_Field__c = 'Date_Of_Death__c',
                Conditional_Operator__c = 'greater or equals',
                Conditional_Value__c = String.valueOf(Date.today().addYears(-2))
            ),
            new Questionnaire_Question__c(
                Questionnaire_Section__c = sectionId,
                Questionnaire__c = questionnaireId,
                Conditional_Object__c = 'Intake__r.srlg_Injured_Party__c',
                Conditional_Field__c = 'First_Name__c',
                Conditional_Operator__c = 'contains',
                Conditional_Value__c = 'test'
            ),
            new Questionnaire_Question__c(
                Questionnaire_Section__c = sectionId,
                Questionnaire__c = questionnaireId,
                Conditional_Object__c = 'Intake__r.litify_pm__Client__c',
                Conditional_Field__c = 'NumberOfEmployees',
                Conditional_Operator__c = 'not equals',
                Conditional_Value__c = '0'
            ),
            new Questionnaire_Question__c(
                Questionnaire_Section__c = sectionId,
                Questionnaire__c = questionnaireId,
                Conditional_Object__c = 'Intake__r.litify_pm__Client__c',
                Conditional_Field__c = 'Intake_Client_Count__c',
                Conditional_Operator__c = 'greater than',
                Conditional_Value__c = '0'
            )
        };
        insert questions;

        List<Answer__c> answers = new List<Answer__c>();
        for (Questionnaire_Question__c q : questions) {
            answers.add(new Answer__c(
                Intake__c = intake.Id,
                Questionnaire_Question__c = q.Id,
                Criteria_Met__c = false
            ));
        }
        insert answers;

        DynamicAnswerCriteriaEvaluator.InputWrapper wrapper = new DynamicAnswerCriteriaEvaluator.InputWrapper();
        wrapper.intakeId = intake.Id;
        wrapper.sectionId = sectionId;

        Test.startTest();
        DynamicAnswerCriteriaEvaluator.evaluateAndCommit(new List<DynamicAnswerCriteriaEvaluator.InputWrapper>{ wrapper });
        Test.stopTest();

        List<Answer__c> updated = [
            SELECT Id, Criteria_Met__c FROM Answer__c WHERE Id IN :answers
        ];

        for (Answer__c a : updated) {
            System.assertEquals(true, a.Criteria_Met__c, 'Expected Criteria_Met__c to be true');
        }
    }

    @IsTest static void verifyDatetimeAndBooleanConditionPasses() {
        Account acct = createTestAccount();
        litify_pm__Case_Type__c caseType = createTestCaseType();
        litify_pm__Intake__c intake = createTestIntake(acct.Id, caseType.Id);
        Map<String, Id> ids = createQuestionnaireWithSection(caseType.Id);
        Id sectionId = ids.get('sectionId');
        Id questionnaireId = ids.get('questionnaireId');
    
        // Datetime in intake is now -24 hours. We compare to a time -7 days ago, so it should pass
        List<Questionnaire_Question__c> questions = new List<Questionnaire_Question__c>{
            new Questionnaire_Question__c(
                Questionnaire_Section__c = sectionId,
                Questionnaire__c = questionnaireId,
                Conditional_Object__c = 'Intake__c',
                Conditional_Field__c = 'Date_Last_Modified_by_API__c',
                Conditional_Operator__c = 'greater than',
                Conditional_Value__c = Datetime.now().addDays(-7).formatGmt('yyyy-MM-dd HH:mm:ss')
        	),
            new Questionnaire_Question__c(
                Questionnaire_Section__c = sectionId,
                Questionnaire__c = questionnaireId,
                Conditional_Object__c = 'Intake__c',
                Conditional_Field__c = 'Test_Intake__c',
                Conditional_Operator__c = 'equals',
                Conditional_Value__c = 'true'
        	)
        };
        insert questions;
    
        List<Answer__c> answers = new List<Answer__c>();
        for (Questionnaire_Question__c q : questions) {
            answers.add(new Answer__c(
                Intake__c = intake.Id,
                Questionnaire_Question__c = q.Id,
                Criteria_Met__c = false
            ));
        }
        insert answers;
    
        DynamicAnswerCriteriaEvaluator.InputWrapper wrapper = new DynamicAnswerCriteriaEvaluator.InputWrapper();
        wrapper.intakeId = intake.Id;
        wrapper.sectionId = sectionId;
    
        Test.startTest();
        DynamicAnswerCriteriaEvaluator.evaluateAndCommit(new List<DynamicAnswerCriteriaEvaluator.InputWrapper>{ wrapper });
        Test.stopTest();
    
        List<Answer__c> updated = [
            SELECT Id, Criteria_Met__c FROM Answer__c WHERE Id IN :answers
        ];

        for (Answer__c a : updated) {
            System.assertEquals(true, a.Criteria_Met__c, 'Expected Criteria_Met__c to be true');
        }
    }
    
    @IsTest static void verifyDatetimeConditionFails() {
        Account acct = createTestAccount();
        litify_pm__Case_Type__c caseType = createTestCaseType();
        litify_pm__Intake__c intake = createTestIntake(acct.Id, caseType.Id);
        Map<String, Id> ids = createQuestionnaireWithSection(caseType.Id);
        Id sectionId = ids.get('sectionId');
        Id questionnaireId = ids.get('questionnaireId');
    
        // Compare to now — but intake datetime is 24 hours ago, so it should fail
        Questionnaire_Question__c question = new Questionnaire_Question__c(
            Questionnaire_Section__c = sectionId,
            Questionnaire__c = questionnaireId,
            Conditional_Object__c = 'Intake__c',
            Conditional_Field__c = 'Date_Last_Modified_by_API__c',
            Conditional_Operator__c = 'greater than',
            Conditional_Value__c = Datetime.now().formatGmt('yyyy-MM-dd HH:mm:ss')
        );
        insert question;
    
        Answer__c answer = new Answer__c(
            Intake__c = intake.Id,
            Questionnaire_Question__c = question.Id,
            Criteria_Met__c = true // intentionally set to true so we can verify it flips to false
        );
        insert answer;
    
        DynamicAnswerCriteriaEvaluator.InputWrapper wrapper = new DynamicAnswerCriteriaEvaluator.InputWrapper();
        wrapper.intakeId = intake.Id;
        wrapper.sectionId = sectionId;
    
        Test.startTest();
        DynamicAnswerCriteriaEvaluator.evaluateAndCommit(new List<DynamicAnswerCriteriaEvaluator.InputWrapper>{ wrapper });
        Test.stopTest();
    
        Answer__c result = [SELECT Criteria_Met__c FROM Answer__c WHERE Id = :answer.Id];
        System.assertEquals(false, result.Criteria_Met__c, 'Expected datetime condition to fail');
    }
    
    @IsTest static void verifyParentAccountNumberFieldCriteria() {
        Account acct = new Account(
            Name = 'Account with Counters',
            litify_pm__Last_Name__c = 'Test Last',
            litify_pm__Phone_Home__c = '555-999-8888',
            NumberOfEmployees = 50,
            Intake_Client_Count__c = 1
        );
        insert acct;
    
        litify_pm__Case_Type__c caseType = createTestCaseType();
        litify_pm__Intake__c intake = createTestIntake(acct.Id, caseType.Id);
        Map<String, Id> ids = createQuestionnaireWithSection(caseType.Id);
        Id sectionId = ids.get('sectionId');
        Id questionnaireId = ids.get('questionnaireId');
    
        // One equals, one greater than operator
        Questionnaire_Question__c q1 = new Questionnaire_Question__c(
            Questionnaire_Section__c = sectionId,
            Questionnaire__c = questionnaireId,
            Conditional_Object__c = 'Intake__r.litify_pm__Client__c',
            Conditional_Field__c = 'NumberOfEmployees',
            Conditional_Operator__c = 'not equals',
            Conditional_Value__c = '10'
        );
    
        Questionnaire_Question__c q2 = new Questionnaire_Question__c(
            Questionnaire_Section__c = sectionId,
            Questionnaire__c = questionnaireId,
            Conditional_Object__c = 'Intake__r.litify_pm__Client__c',
            Conditional_Field__c = 'Intake_Client_Count__c',
            Conditional_Operator__c = 'greater than',
            Conditional_Value__c = '0'
        );
    
        insert new List<Questionnaire_Question__c>{ q1, q2 };
    
        List<Answer__c> answers = new List<Answer__c>{
            new Answer__c(Intake__c = intake.Id, Questionnaire_Question__c = q1.Id, Criteria_Met__c = false),
            new Answer__c(Intake__c = intake.Id, Questionnaire_Question__c = q2.Id, Criteria_Met__c = false)
        };
        insert answers;
    
        DynamicAnswerCriteriaEvaluator.InputWrapper wrapper = new DynamicAnswerCriteriaEvaluator.InputWrapper();
        wrapper.intakeId = intake.Id;
        wrapper.sectionId = sectionId;
    
        Test.startTest();
        DynamicAnswerCriteriaEvaluator.evaluateAndCommit(new List<DynamicAnswerCriteriaEvaluator.InputWrapper>{ wrapper });
        Test.stopTest();
    
        Map<Id, Answer__c> updated = new Map<Id, Answer__c>([
            SELECT Id, Criteria_Met__c FROM Answer__c WHERE Id IN :answers
        ]);
    
        System.assertEquals(true, updated.get(answers[0].Id).Criteria_Met__c, 'Caller Count should not equal 10');
        System.assertEquals(true, updated.get(answers[1].Id).Criteria_Met__c, 'Client Count should be greater than 0');
    }
}