unpackaged/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Answer__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <label>Intake</label>
    <referenceTo>litify_pm__Intake__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Answer__c/fields/Questionnaire_Question__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire_Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question</label>
    <referenceTo>Questionnaire_Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Questionnaire__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>litify_pm__Case_Type__c.litify_pm__Is_Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>litify_pm__Case_Type__c</referenceTo>
    <relationshipLabel>Questionnaires</relationshipLabel>
    <relationshipName>Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire__c/fields/isAvailable__c.field-meta.xml
<CustomField>
    <fullName>isAvailable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Question__c/Questionnaire_Question__c.object-meta.xml
<CustomObject>
    <label>Questionnaire Question</label>
    <nameField>
        <label>Questionnaire Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaire Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Questionnaire_Question__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Questionnaire Questions</relationshipLabel>
    <relationshipName>QuestionnaireQuestion</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Question__c/fields/Questionnaire_Section__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire_Section__c</fullName>
    <label>Questionnaire Section</label>
    <referenceTo>Questionnaire_Section__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>QuestionSection</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Section__c/Questionnaire_Section__c.object-meta.xml
<CustomObject>
    <label>Questionnaire Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaire Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Questionnaire_Section__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Questionnaire</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Section__c/fields/Section_Category__c.field-meta.xml
<CustomField>
    <fullName>Section_Category__c</fullName>
    <label>Section Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Short Form</fullName>
            </value>
            <value>
                <fullName>Long Form</fullName>
            </value>
            <value>
                <fullName>Qualifying</fullName>
                <isActive>false</isActive>
                <label>Qualifying</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DynamicQuestionsControllerTest.cls
@IsTest
public with sharing class DynamicQuestionsControllerTest {

    @TestSetup
    static void setup() {
        // Create test Accounts
        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < 10; i++) {
            accounts.add(new Account(
                Name = 'Test Account ' + i,
                litify_pm__Last_Name__c = 'Last Name ' + i,
                litify_pm__Phone_Home__c = '123-456-789' + i
            ));
        }
        insert accounts;

        // Create Case Type
        litify_pm__Case_Type__c caseType = new litify_pm__Case_Type__c(
            Name = 'Test Case Type',
            litify_pm__Is_Available__c = true
        );
        insert caseType;

        // Create Questionnaire
        Questionnaire__c questionnaire = new Questionnaire__c(
            isActive__c = true,
            isAvailable__c = true,
            Case_Type__c = caseType.Id
        );
        insert questionnaire;

        // Create Section
        Questionnaire_Section__c section = new Questionnaire_Section__c(
            Name = 'Section A',
            Questionnaire__c = questionnaire.Id,
            Section_Category__c = 'Short Form'
        );
        insert section;
        
        // Create Question (no conditional logic)
        Questionnaire_Question__c question = new Questionnaire_Question__c(
            Questionnaire_Section__c = section.Id,
            Questionnaire__c = questionnaire.Id
        );
        insert question;

        // Create Intake
        litify_pm__Intake__c intake = new litify_pm__Intake__c(
            litify_pm__Client__c = accounts[0].Id,
            litify_pm__Case_Type__c = caseType.Id,
            Calling_on_behalf_of_you_or_loved_one__c = 'Self'
        );
        insert intake;

        // Create Answer__c records linked to Intake and Section
        List<Answer__c> answers = new List<Answer__c>();
        for (Integer i = 0; i < 5; i++) {
            answers.add(new Answer__c(
                Intake__c = intake.Id,
                Questionnaire_Question__c = question.Id,
                Answer__c = 'Initial Value ' + i
            ));
        }
        insert answers;
    }
 
    @IsTest
    static void testGetMultiLookupRecords() {
        // Test the getMultiLookupRecords method
        Test.startTest();
        List<SObject> results = DynamicQuestionsController.getMultiLookupRecords('Account');
        Test.stopTest();

        // Assert the results
        System.assertNotEquals(null, results, 'Results should not be null');
        System.assertEquals(10, results.size(), 'Results should contain 10 records');
    }

    @IsTest
    static void testUpdateAnswer() {
        // Get an existing Answer__c record
        Answer__c answer = [SELECT Id, Answer__c FROM Answer__c LIMIT 1];
        String newValue = 'Updated Value';

        // Test the updateAnswer method
        Test.startTest();
        DynamicQuestionsController.updateAnswer(answer.Id, newValue);
        Test.stopTest();

        // Verify the update
        Answer__c updatedAnswer = [SELECT Id, Answer__c FROM Answer__c WHERE Id = :answer.Id];
        System.assertEquals(newValue, updatedAnswer.Answer__c, 'Answer__c field should be updated');
    }

    @IsTest
    static void testUpdateEncryptedAnswer() {
        // Get an existing Answer__c record
        Answer__c answer = [SELECT Id, Answer__c FROM Answer__c LIMIT 1];
        String encryptedValue = '****';

        // Test the updateAnswer method for Encrypted type
        Test.startTest();
        DynamicQuestionsController.updateAnswer(answer.Id, encryptedValue);
        Test.stopTest();

        // Verify the update
        Answer__c updatedAnswer = [SELECT Id, Answer__c FROM Answer__c WHERE Id = :answer.Id];
        System.assertEquals(encryptedValue, updatedAnswer.Answer__c, 'Answer__c field should be updated with **** for Encrypted type');
    }
    
    @IsTest
    static void testGetMultiLookupRecords_BlankObjectName() {
        Test.startTest();
        try {
            DynamicQuestionsController.getMultiLookupRecords('');
            System.assert(false, 'Expected AuraHandledException for blank object name');
        } catch (AuraHandledException e) {
            System.debug('Caught expected AuraHandledException');
            Test.stopTest();
            return;
        }
        Test.stopTest();
        System.assert(false, 'Expected exception but none was thrown');
    }
    
    @IsTest
    static void testFetchLookupData_WithSearchKey() {
        Account acc=[Select Id, Name, litify_pm__Last_Name__c from Account where litify_pm__Last_Name__c='Last Name 0' limit 1];
        List<Id> accIds=new List<Id>();
        accIds.add(acc.Id);
        List<SObject> results = DynamicQuestionsController.fetchLookupData('', 'Account',accIds);
        System.debug('FetchLookupData results: ' + results);
        System.assert(!results.isEmpty(), 'Should return at least one matching record');
        System.assertEquals('Last Name 0', (String)results[0].get('Name'));
    }
    
    @IsTest
    static void testFetchLookupRecordById_Valid() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        SObject result = DynamicQuestionsController.fetchLookupRecordById(acc.Id, 'Account');
        System.assertNotEquals(null, result, 'Should return a matching record');
    }
    
    @IsTest
    static void testFetchLookupRecordById_BlankInputs() {
        Test.startTest();
        try {
            DynamicQuestionsController.fetchLookupRecordById('', '');
            System.assert(false, 'Expected AuraHandledException for missing inputs');
        } catch (AuraHandledException e) {
            System.debug('Caught expected AuraHandledException');
            Test.stopTest();
            return;
        }
        Test.stopTest();
        System.assert(false, 'Expected exception but none was thrown');
    }

    @IsTest
    static void testUpdateAnswer_InvalidId() {
        // Get a real answer and delete it
        Answer__c temp = [SELECT Id FROM Answer__c LIMIT 1];
        delete temp;
    
        Test.startTest();
        try {
            DynamicQuestionsController.updateAnswer(temp.Id, 'Should Fail');
            System.assert(false, 'Expected AuraHandledException to be thrown');
        } catch (AuraHandledException e) {
            System.debug('Caught expected AuraHandledException');
            return; // ✅ Do not assert message — Salesforce masks it as "Script-thrown exception"
        }
        Test.stopTest();
        System.assert(false, 'Expected exception but none was thrown');
    }
}