unpackaged/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Answer__c/fields/Criteria_Met__c.field-meta.xml
<CustomField>
    <fullName>Criteria_Met__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Criteria Met</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Answer__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <label>Intake</label>
    <referenceTo>litify_pm__Intake__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Answer__c/fields/Questionnaire_Question__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire_Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question</label>
    <referenceTo>Questionnaire_Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Questionnaire__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>litify_pm__Case_Type__c.litify_pm__Is_Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>litify_pm__Case_Type__c</referenceTo>
    <relationshipLabel>Questionnaires</relationshipLabel>
    <relationshipName>Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire__c/fields/isAvailable__c.field-meta.xml
<CustomField>
    <fullName>isAvailable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Question__c/Questionnaire_Question__c.object-meta.xml
<CustomObject>
    <label>Questionnaire Question</label>
    <nameField>
        <label>Questionnaire Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaire Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Questionnaire_Question__c/fields/Conditional_Field__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Field__c</fullName>
    <label>Conditional Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Question__c/fields/Conditional_Object__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Object__c</fullName>
    <label>Conditional Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake__c</fullName>
                <label>Intake</label>
            </value>
            <value>
                <fullName>Intake__r.Campaign_Case__c</fullName>
                <label>Campaign Case</label>
            </value>
            <value>
                <fullName>Questionnaire_Question__c</fullName>
                <label>Questionnaire Question</label>
            </value>
            <value>
                <fullName>Questionnaire_Question__r.Questionnaire_Section__c</fullName>
                <label>Questionnaire Section</label>
            </value>
            <value>
                <fullName>Intake__r.litify_pm__Client__c</fullName>
                <label>Account</label>
            </value>
            <value>
                <fullName>Intake__r.srlg_Injured_Party__c</fullName>
                <label>Injured Party</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Question__c/fields/Conditional_Value__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Value__c</fullName>
    <inlineHelpText>Criteria that must be met to show the question. If left blank then it will always show.</inlineHelpText>
    <label>Conditional Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Question__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Questionnaire Questions</relationshipLabel>
    <relationshipName>QuestionnaireQuestion</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Question__c/fields/Questionnaire_Section__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire_Section__c</fullName>
    <label>Questionnaire Section</label>
    <referenceTo>Questionnaire_Section__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>QuestionSection</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Section__c/Questionnaire_Section__c.object-meta.xml
<CustomObject>
    <label>Questionnaire Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaire Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Questionnaire_Section__c/fields/Conditional_Object__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Object__c</fullName>
    <label>Conditional Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake__c</fullName>
                <label>Intake</label>
            </value>
            <value>
                <fullName>Intake__r.Campaign_Case__c</fullName>
                <label>Campaign Case</label>
            </value>
            <value>
                <fullName>Intake__r.litify_pm__Client__c</fullName>
                <label>Account</label>
            </value>
            <value>
                <fullName>Intake__r.srlg_Injured_Party__c</fullName>
                <label>Injured Party</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Section__c/fields/Conditional_Operator__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Operator__c</fullName>
    <label>Conditional Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Operators</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Section__c/fields/Conditional_Value__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Value__c</fullName>
    <inlineHelpText>Criteria that would need to be met to be visible. If blank then always visible.</inlineHelpText>
    <label>Conditional Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Section__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Questionnaire</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Questionnaire_Section__c/fields/Section_Category__c.field-meta.xml
<CustomField>
    <fullName>Section_Category__c</fullName>
    <label>Section Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Short Form</fullName>
            </value>
            <value>
                <fullName>Long Form</fullName>
            </value>
            <value>
                <fullName>Qualifying</fullName>
                <isActive>false</isActive>
                <label>Qualifying</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Operators.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>equals</fullName>
    </customValue>
    <customValue>
        <fullName>not equals</fullName>
    </customValue>
    <customValue>
        <fullName>less than</fullName>
    </customValue>
    <customValue>
        <fullName>less or equals</fullName>
    </customValue>
    <customValue>
        <fullName>greater than</fullName>
    </customValue>
    <customValue>
        <fullName>greater or equals</fullName>
    </customValue>
    <customValue>
        <fullName>starts with</fullName>
    </customValue>
    <customValue>
        <fullName>ends with</fullName>
    </customValue>
    <customValue>
        <fullName>contains</fullName>
    </customValue>
    <description>Valid Operators for dynamic criteria calculations</description>
    <masterLabel>Operators</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AnswerCriteriaMatchTests.cls
@IsTest
public class AnswerCriteriaMatchTests {
    
    static final Datetime FIXED_DATETIME = Datetime.newInstanceGmt(2024, 1, 1, 12, 0, 0);
    static final String FIXED_DATETIME_STRING = FIXED_DATETIME.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');

    static litify_pm__Intake__c createTestIntake() {
        Account acct = new Account(
            Name = 'Test Account',
            litify_pm__Last_Name__c = 'Test Last',
            litify_pm__Phone_Home__c = '555-123-4567'
        );
        insert acct;

        litify_pm__Case_Type__c caseType = new litify_pm__Case_Type__c(Name = 'QACaseType', litify_pm__Is_Available__c = true);
        insert caseType;

        litify_pm__Intake__c intake = new litify_pm__Intake__c(
            litify_pm__Client__c = acct.Id,
            litify_pm__Case_Type__c = caseType.Id,
            Count_of_E_Sig_Documents__c = 10,
            Allow_email_send__c = true,
            Injured_Party_Birthdate__c = Date.newInstance(2024, 1, 1),
            Date_Last_Modified_by_API__c = FIXED_DATETIME,
            Campaign_Partner_Packet_Name__c = 'Test Campaign'
        );

        insert intake;

        return intake;
    }

    static void runMatchTest(String field, String op, String val, String type) {
        litify_pm__Intake__c intake = createTestIntake();

        Questionnaire__c questionnaire = new Questionnaire__c(
            Case_Type__c = intake.litify_pm__Case_Type__c,
            isActive__c = true,
            isAvailable__c = true
        );
        insert questionnaire;

        Questionnaire_Section__c section = new Questionnaire_Section__c(
            Name = 'QA Section',
            Questionnaire__c = questionnaire.Id,
            Section_Category__c = 'Short Form',
            Conditional_Object__c = 'litify_pm__Intake__c',
            Conditional_Field__c = field,
            Conditional_Operator__c = op,
            Conditional_Value__c = val
        );
        insert section;

        Questionnaire_Question__c question = new Questionnaire_Question__c(
            Questionnaire__c = questionnaire.Id,
            Questionnaire_Section__c = section.Id
        );
        insert question;

        Answer__c answer = new Answer__c(
            Questionnaire_Question__c = question.Id,
            Intake__c = intake.Id,
            Criteria_Met__c = false
        );
        insert answer;

        DynamicAnswerCriteriaEvaluator.InputWrapper wrapper = new DynamicAnswerCriteriaEvaluator.InputWrapper();
        wrapper.intakeId = intake.Id;
        wrapper.sectionId = section.Id;

        Test.startTest();
        DynamicAnswerCriteriaEvaluator.evaluateAndCommit(new List<DynamicAnswerCriteriaEvaluator.InputWrapper>{ wrapper });
        Test.stopTest();
    }

    // === BOOLEAN ===
    @IsTest static void testEqualsBoolean() {
        runMatchTest('Allow_email_send__c', 'equals', 'true', 'boolean');
    }
    @IsTest static void testNotEqualsBoolean() {
        runMatchTest('Allow_email_send__c', 'not equals', 'false', 'boolean');
    }

    // === NUMBER ===
    @IsTest static void testEqualsNumber() {
        runMatchTest('Count_of_E_Sig_Documents__c', 'equals', '10', 'number');
    }
    @IsTest static void testNotEqualsNumber() {
        runMatchTest('Count_of_E_Sig_Documents__c', 'not equals', '5', 'number');
    }
    @IsTest static void testLessThanNumber() {
        runMatchTest('Count_of_E_Sig_Documents__c', 'less than', '11', 'number');
    }
    @IsTest static void testLessOrEqualsNumber() {
        runMatchTest('Count_of_E_Sig_Documents__c', 'less or equals', '10', 'number');
    }
    @IsTest static void testGreaterThanNumber() {
        runMatchTest('Count_of_E_Sig_Documents__c', 'greater than', '9', 'number');
    }
    @IsTest static void testGreaterOrEqualsNumber() {
        runMatchTest('Count_of_E_Sig_Documents__c', 'greater or equals', '10', 'number');
    }

    // === DATE ===
    @IsTest static void testDateEquals() {
        runMatchTest('Injured_Party_Birthdate__c', 'equals', '2024-01-01', 'date');
    }
    @IsTest static void testDateNotEquals() {
        runMatchTest('Injured_Party_Birthdate__c', 'not equals', '2024-01-02', 'date');
    }
    @IsTest static void testDateLessThan() {
        runMatchTest('Injured_Party_Birthdate__c', 'less than', '2024-01-02', 'date');
    }
    @IsTest static void testDateLessOrEquals() {
        runMatchTest('Injured_Party_Birthdate__c', 'less or equals', '2024-01-01', 'date');
    }
    @IsTest static void testDateGreaterThan() {
        runMatchTest('Injured_Party_Birthdate__c', 'greater than', '2023-12-31', 'date');
    }
    @IsTest static void testDateGreaterOrEquals() {
        runMatchTest('Injured_Party_Birthdate__c', 'greater or equals', '2024-01-01', 'date');
    }

    // === DATETIME ===
    @IsTest static void testDateTimeEquals() {
        runMatchTest('Date_Last_Modified_by_API__c', 'equals', FIXED_DATETIME_STRING, 'datetime');
    }
    @IsTest static void testDateTimeNotEquals() {
        runMatchTest('Date_Last_Modified_by_API__c', 'not equals', FIXED_DATETIME_STRING, 'datetime');
    }
    @IsTest static void testDateTimeLessThan() {
        runMatchTest('Date_Last_Modified_by_API__c', 'less than', FIXED_DATETIME_STRING, 'datetime');
    }
    @IsTest static void testDateTimeLessOrEquals() {
        runMatchTest('Date_Last_Modified_by_API__c', 'less or equals', FIXED_DATETIME_STRING, 'datetime');
    }
    @IsTest static void testDateTimeGreaterThan() {
        runMatchTest('Date_Last_Modified_by_API__c', 'greater than', FIXED_DATETIME_STRING, 'datetime');
    }
    @IsTest static void testDateTimeGreaterOrEquals() {
        runMatchTest('Date_Last_Modified_by_API__c', 'greater or equals', FIXED_DATETIME_STRING, 'datetime');
    }

    // === STRING ===
    @IsTest static void testStringEquals() {
        runMatchTest('Campaign_Partner_Packet_Name__c', 'equals', 'Test Campaign', 'string');
    }
    @IsTest static void testStringNotEquals() {
        runMatchTest('Campaign_Partner_Packet_Name__c', 'not equals', 'Wrong Name', 'string');
    }
    @IsTest static void testStringStartsWith() {
        runMatchTest('Campaign_Partner_Packet_Name__c', 'starts with', 'Test', 'string');
    }
    @IsTest static void testStringEndsWith() {
        runMatchTest('Campaign_Partner_Packet_Name__c', 'ends with', 'Campaign', 'string');
    }
    @IsTest static void testStringContains() {
        runMatchTest('Campaign_Partner_Packet_Name__c', 'contains', 'ampa', 'string');
    }

    // ❌ Invalid operator for strings - fallback test (should return false and debug unsupported op)
    @IsTest static void testUnsupportedStringOperator() {
        runMatchTest('litify_pm__Client__r.Name', 'greater than', 'Aardvark', 'string');
    }
}