unpackaged/main/default/objects/Etech_API_Setting__c/Etech_API_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Etech API Setting</label>
</CustomObject>

unpackaged/main/default/objects/Etech_API_Setting__c/fields/Debugging__c.field-meta.xml
<CustomField>
    <fullName>Debugging__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Debugging?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log (Outgoing)</label>
    <nameField>
        <label>Integration Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Logs (Outgoing)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Integration_Log__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>litify_pm__Intake__c</referenceTo>
    <relationshipLabel>Integration Logs (Outgoing)</relationshipLabel>
    <relationshipName>Integration_Logs_Outgoing</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <label>Stop</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/Etech_Logger.cls
public with sharing class Etech_Logger {    
    public static final String DEBUG_PREFIX = UserInfo.getUserName() + '~ ';
    
    public static Etech_API_Setting__c settings {
        get {
            return Etech_API_Setting__c.getOrgDefaults();
        }
        set;
    }
    
    @TestVisible static Integration_Log__c[] logs = new Integration_Log__c[]{};
        public class Log {
            Integration_Log__c theLog = new Integration_Log__c();
            public Log(LoggingLevel level, String name, Object detail, string relatedRecId) {
                theLog.Level__c = String.valueOf((null != level) ? level : LoggingLevel.NONE);
                theLog.Name = (null != name) ? name : '(unnamed)';
                theLog.Log__c = (null != detail) ? String.valueOf(detail) : '(no detail)';
                theLog.Intake__c = !string.isEmpty(relatedRecId) ? relatedRecId : null;            
                start();
                logs.add(theLog);
            }
            
            public void start() {
                theLog.Start__c = System.currentTimeMillis();
            }
            
            public void stop() {
                theLog.Stop__c = System.currentTimeMillis();
            }
            
            public void setRequest(HttpRequest r) {
                theLog.Request__c = (null != r) ? (r.toString()  + '\n\nBody: ' + r.getBody()) : null;
            }
            
            public void setResponse(HttpResponse r) {
                theLog.Response__c = (null != r) ? (r.toString()  + '\n\nBody: ' + r.getBody()) : null;
            }
        }
    
    public static void writeLogs() {
        // get the user-specified log levels to save
        if(settings.Debugging__c){
            if (!logs.isEmpty()) {
                for (Integration_Log__c l : logs) {
                    l.Stop__c = (null == l.Stop__c) ? System.currentTimeMillis() : l.Stop__c;
                }
                Database.DMLOptions dmlOptions = new Database.DMLOptions();
                dmlOptions.allowFieldTruncation = true;
                Database.insert(logs, dmlOptions);
            }
            logs.clear();
        }
    }
}