unpackaged/main/default/objects/Integration__mdt/fields/Base_SObject__c.field-meta.xml
<CustomField>
    <fullName>Base_SObject__c</fullName>
    <label>Base SObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Integrations</relationshipLabel>
    <relationshipName>Integrations</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

unpackaged/main/default/objects/Integration__mdt/fields/Debugging__c.field-meta.xml
<CustomField>
    <fullName>Debugging__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Debugging?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Integration__mdt/fields/Log_Days_to_Keep__c.field-meta.xml
<CustomField>
    <fullName>Log_Days_to_Keep__c</fullName>
    <label>Log Days to Keep</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Integration__mdt/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <label>Log Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Integration__mdt/fields/Sync_Date_Field__c.field-meta.xml
<CustomField>
    <fullName>Sync_Date_Field__c</fullName>
    <label>Sync Date Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SaddleRockSyncHandler.cls
public without sharing class SaddleRockSyncHandler extends SaddleRockMappingHelper {
    public Map<string,object> SaddleRockSyncHandler(string integrationId, List<Map<String, Object>> data) {
        System.debug('SaddleRockSyncHandler started');
        Integration__mdt[] configs = new Integration__mdt[]{};
        
        if(Test.isRunningTest()){
            Integration__mdt testIntegration = SaddleRockTestDataFactory.generateTestIntegration();
            configs.add(testIntegration);
        }
        else {
            configs = [SELECT Id, Name__c, Log_Level__c, Log_Days_to_Keep__c, Debugging__c, Active__c, Base_SObject__r.QualifiedApiName, Sync_Date_Field__c 
                                    FROM Integration__mdt 
                                    WHERE Id = :integrationId AND Active__c = true 
                                    LIMIT 1];
        }

        SObject[] recordsToUpdate = new SObject[]{};
        SaddleRockUtils.integrationId = Test.isRunningTest() ? configs[0].Id : integrationId;

        try {
            recordsToUpdate = jsonToRecords(integrationId, configs[0].Base_SObject__r.QualifiedApiName, configs[0].Sync_Date_Field__c, data);
        
            System.debug(recordsToUpdate);

            if(recordsToUpdate != null && recordsToUpdate.size() > 0){
                update recordsToUpdate;
            }
            return new Map<string,object>{
                'success' => true,
                'data' => 'OK'
            };
        }
        catch(Exception e){
            return new Map<string,object>{
                'success' => false,
                'data' => e.getMessage()
            };
        }
    }
}